services:
  - type: web
    name: emotion-api
    env: docker
    region: frankfurt
    plan: free
    dockerfilePath: Dockerfile
    rootDir: backend
    buildCommand: ""
    startCommand: ""
    autoDeploy: true
